name: Build and Deploy with Oryx++ GHA

on:
  workflow_dispatch:   
  push:
    branches: 
      [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
        with:
          ref: main
          
      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v0
        with:
          acrName: ca26327fca9eacr
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
          resourceGroup: jrs-hw4   
          containerAppName: jrs-hw4-aca1
          appSourcePath: ${{ github.workspace }}                  
          imageToBuild: ca26327fca9eacr.azurecr.io/jrs-hw4-aca1:${{ github.sha }}
